# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a492873797ea660dcb0de6d95d8d5bac"
name = "whatsapp-mern-app"
application_url = "https://whatsapp-mern-web.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"


[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "https://whatsapp-mern-backend-sidn.onrender.com/api/shopify/webhook"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://whatsapp-mern-backend-sidn.onrender.com/api/shopify/webhook"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
    "https://whatsapp-mern-web.onrender.com/auth/callback",
    "https://whatsapp-mern-web.onrender.com/auth/shopify/callback",
    "https://whatsapp-mern-web.onrender.com/api/auth/callback"
]
