# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a492873797ea660dcb0de6d95d8d5bac"
name = "whatsapp-mern-app"
application_url = "http://ecswhatsup.ecodesoft.net"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://ecswhatsup-backend.ecodesoft.net/api/shopify/webhook"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes"

[auth]
redirect_urls = [
  "http://ecswhatsup.ecodesoft.net/auth/callback",
  "http://ecswhatsup.ecodesoft.net/auth/shopify/callback",
  "http://ecswhatsup.ecodesoft.net/api/auth/callback"
]
